# Generated by Django 4.0.6 on 2024-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_projectsdata_created_date_projectsdata_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('extra1', models.CharField(max_length=2000)),
                ('extra2', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='showcase\\static\\profile\\')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
