# Generated by Django 4.0.6 on 2024-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_alter_profiledata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='extra1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='extra2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
