# Generated by Django 4.0.6 on 2024-05-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_alter_profiledata_extra1_alter_profiledata_extra2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='title',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
