# Generated by Django 4.0.6 on 2024-05-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_profiledata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdata',
            name='description',
            field=models.TextField(),
        ),
    ]
